package com.cice.hibernate.pojo;
// Generated 22-nov-2017 20:05:17 by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private Integer usuariosid;
     private String user;
     private String pass;
     private String description;

    public Usuarios() {
    }

	
    public Usuarios(String user, String pass) {
        this.user = user;
        this.pass = pass;
    }
    public Usuarios(String user, String pass, String description) {
       this.user = user;
       this.pass = pass;
       this.description = description;
    }
   
    public Integer getUsuariosid() {
        return this.usuariosid;
    }
    
    public void setUsuariosid(Integer usuariosid) {
        this.usuariosid = usuariosid;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


